#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  annotations:
#    kompose.cmd: kompose convert -f docker-compose.yaml
#    kompose.version: 1.28.0 (c4137012e)
#  creationTimestamp: null
#  labels:
#    app: action-server
#  name: action-server
#  namespace: default
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: action-server
#  strategy: {}
#  template:
#    metadata:
#      annotations:
#        kompose.cmd: kompose convert -f docker-compose.yaml
#        kompose.version: 1.28.0 (c4137012e)
#      creationTimestamp: null
#      labels:
#        io.kompose.network/june-15-rasa-rasa-network: "true"
#        app: action-server
#    spec:
#      containers:
#        - name: action-server
#          image: action:a1
#          imagePullPolicy: Never
#          ports:
#            - containerPort: 5055
#          resources: {}
#          volumeMounts:
#            - mountPath: /app/config/endpoints.yml
#              name: rasa-config-volume
#             # subPath: endpoints.yml
#              readOnly: true
#      restartPolicy: Always
#      volumes:
#        - name: rasa-config-volume
#          configMap:
#            name: rasa-config
#          #readOnly: true
#          #items:
#           # - key: endpoints.yml
#           #   path: endpoints.yml
#         # command: ["rasa" ,"run" ,"actions" ,"port" ,"5055"]
##      imagePullSecrets:
##        - name: k8s-secret
##      containers:
##        - image: nikhilsg/nick_007:a1
##          name: action-server
##          ports:
##            - containerPort: 5055
##          readinessProbe:           ##1
##            httpGet:
##              path: /actions
##              port: 5055
##            initialDelaySeconds: 5
##            periodSeconds: 5
##            successThreshold: 1
##            envFrom:
##              - configMapRef:
##                  name: chatbot-config   #2
#      #    resources: {}
#      #restartPolicy: Always
#status: {}